spring:
  application:
    name: server
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://localhost:3306/db
    username: admin
    password: iikotozukumenoyumekarasametawatashinonounaikankyouwa
    #username: root
    #password: password
    driver-class-name: com.mysql.cj.jdbc.Driver
  mail:
    host: smtp.gmail.com
    port: 587
    link-exam: https://exam/
    username: tetrad.unity4@gmail.com
    password: azdecgbbtnvciazx
    properties:
      mail:
        debug: false
        transport:
          protocol: smtp
        smtp:
          auth: true
          starttls:
            enable: true

cloud:
  aws:
    credentials:
      access-key:
      secret-key:
    region:
      static: us-east-2
    stack:
      auto: false

application:
  bucket:
    name: javatechiestorage

first-chief-teacher:
  email: maksimmankivskiy04@gmail.com
  password: q21we43rt65y
  first-name: Максим
  last-name: Маньківський