spring:
  application:
    name: server
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://bybz3tyvn8bdqh4iwea6-mysql.services.clever-cloud.com:3306/bybz3tyvn8bdqh4iwea6
    username: ue83oonudqbjcu3r
    password: bj9TpcD116tzR5e8OGfn
    driver-class-name: com.mysql.cj.jdbc.Driver
  mail:
    host: smtp.gmail.com
    port: 587
    link-exam: 'https://exam/'
    username: tetrad.unity4@gmail.com
    password: azdecgbbtnvciazx
    properties:
      mail:
        debug: false
        transport:
          protocol: smtp
        smtp:
          auth: true
          starttls:
            enable: true
first-chief-teacher:
  email: maksik@gmail.com
  password: q21we43rt65y
  first-name: Максік
  last-name: Манько